### ISSUE TITLE
Local violations should be non-trapping

### ISSUE THREAD

**Issue by davidchisnall** [microsoft/cheriot-sail#20]
Violations of permit-store-local should silently clear the tag bit.  This changes was made in Ibex, because it makes it possible to have a non-trapping memcpy without needing to inspect every byte.  We should update the spec.

**Comment by vmurali** [comment]
This implies that there is no PERMIT_STORE_LOCAL_CAPABILITY Violation anymore. Is that correct?

**Comment by davidchisnall** [comment]
Correct, this will no longer be an exception, you will get an invalid tag exception cause after tag clearing.

**Comment by vmurali** [comment]
Yes. I meant, since PERMIT_STORE_LOCAL_CAPABILITY Violation cannot be caused anymore, that should be removed from the list of violations in Table 7.3 of the manual (https://www.microsoft.com/en-us/research/uploads/prod/2023/02/cheriot-63e11a4f1e629.pdf)

**Comment by davidchisnall** [comment]
Yup, though we may want to keep it as a reserved exception code. We were discussing having a debug mode that made all (or a configurable subset of) the tag-clearing operations trap and it might be useful there.
