### ISSUE TITLE
Sealing and Unsealing Authorities for addresses rather than otypes

### ISSUE THREAD

**Issue by vmurali** [microsoft/cheriot-sail#29]
The current sealing and unsealing authorities permit sealing and unsealing of specific otypes. This restricts the number of different data authorities to 7 (otype encoded between 9 to 15). It would be useful to have a address-based sealing/unsealing authority as follows:

- Compartment A has a sealing and unsealing authority for a range of addresses.
- Compartment A can pass any cap within that range after sealing it, using the sealing authority for that range, to compartment B
- When the compartment B calls a function of compartment A by passing the sealed cap, compartment A can unseal the cap using the unsealing authority for that range.

This gives a way to have a lot more "types" for sealing.

Is there any issue in having such a sealing type? Perhaps, one of the 7 data sealing otypes can be allotted for such an address-based sealing so that the hardware can perform the necessary checks. I agree that the SW can use one of the otypes and perform such a check manually, but it would be simpler to do the checks in hardware.

**Comment by davidchisnall** [comment]
The virtualised sealing mechanism in the RTOS uses the non-architectural sealing ranges.

**Comment by davidchisnall** [comment]
See: https://cheriot.org/book/shared_heap.html#token_apis

**Comment by vmurali** [comment]
This looks like the interface I am talking about, thanks!

The only difference is, instead of putting the sealing type in the header, I was suggesting using the address as the sealing type and performing the "sealing type is authorized by the unsealing authority" check by ensuring that the address of the sealed object is within the authority's bounds.

The software check (using a header) gives more flexibility in terms of not being contiguous. So maybe a new architectural mechanism based on addresses is a wash.

**Comment by davidchisnall** [comment]
> I was suggesting using the address as the sealing type and performing the "sealing type is authorized by the unsealing authority" check by ensuring that the address of the sealed object is within the authority's bounds.

This approach would not be usable with dynamic allocations. Ownership of a range of the address space is a temporal property and so we would have to revoke sealing keys as well. In addition, each allocation would need a separate sealing key, so you’d have to keep a dictionary of unseal capabilities, at which point you may as well just hand out capabilities with all permissions removed and look up the real one on entry.

The unseal operation is a library call and so is on the order of 10 cycles, which means that we can use it on fast paths and use the same type for statically provisioned and dynamically allocated capabilities.
