### ISSUE TITLE
Intended use for reserved bit in capabilities

### ISSUE THREAD

**Issue by vmurali** [microsoft/cheriot-sail#36]
Sorry to raise it as an issue, perhaps this should go into a mailing list - please let me know if you have one.

I was wondering if there's any intended use for the reserved bit in the CherIoT? The main reason I would like to reclaim the space is to have better granularities for bigger bounds, between 2^(9+14) to 2^32. It looks like lack of big buffer support in CherIoT is a reason to avoid it even for applications that don't require 64-bit datatypes except for big buffer references.

**Comment by nwf-msr** [comment]
FWIW, the closest thing we have to a mailing list at the moment is the (hard-to-discover) https://github.com/microsoft/cheriot-rtos/discussions .  We'll probably move that somewhere more convenient and advertised "soon".

To the point of the reserved bit, I think we (well, at least I; I shouldn't claim to speak _too much_ for everyone involved) want it to remain reserved for as long as possible.

I think, specifically, that using our last bit to increase the exponent size is not a good use thereof.  In general, CHERIoT is targeting systems whose contiguous regions of physical memory are unlikely to approach 2^24 bytes, and so it's unclear that capabilities with bounds larger than 2^23 are sensible outside of bootstrap (and even then, maybe not, if we could do without).  For the targeted class of devices, the only justifications I've encountered for 32 bit address spaces are

  1. that it's a convenient word size (but CHERI decouples "pointer", "address", and "word" sizes even more than traditional architectures) or
  2. it enables page-based MMIO access control with a MMU, by scattering MMIO ports sparsely across pages (but CHERIoT certainly doesn't need the hardware to do that).

(Maybe one still wants a MMU to provide more or less transparent emulation of a V > P address space, and CHERIoT, in principle, could work with such systems, but even so, 28 bits of VA is likely sufficient.)

Generalizing to bit pressure in general: we've even considered _reducing_ the size of the _address_ field to 28 bits, to better reflect this aspect of the target platforms, free up some wires in the hardware, and allow us to grow the otype or permission fields if a need arose.  At that point, the five missing exponent values really don't feel important.

As a much-further-future consideration, some of the "mix capabilities of different sizes within the same system" proposals require essentially in-band "format" bit(s) in addition to the out-of-band tag bits, and having a reserved bit in the design leaves that door open.

**Comment by vmurali** [comment]
Thanks for the explanation. Feel-free to close this issue, as it's not really an issue. I am fine with your super long term plans for that bit.
