### ISSUE TITLE
Type error while building with upstream Sail

### ISSUE THREAD

**Issue by marnovandermaas** [microsoft/cheriot-sail#56]
I am building with upstream Sail, commit: b81e2823f8b4ffcf14cb0b11c260d79d3a19b0dc

I'm getting the following type error:
```
Type error:
src/cheri_riscv_types.sail:143.31-33:
143 |    EXC_LOAD_CAP_PAGE_FAULT => 26,
    |                               ^^
    | int(26) is not a subtype of {('e : Int), (0 <= 'e & 'e <= 2). int('e)}
    | as (0 <= 'ex2448167 & 'ex2448167 <= 2) could not be proven
    | 
    | type variable 'ex2448167:
    | src/cheri_riscv_types.sail:143.31-33:
    | 143 |    EXC_LOAD_CAP_PAGE_FAULT => 26,
    |     |                               ^^ bound here
    |     | has constraint: 26 == 'ex2448167
```

In the code the type definition says the execution code must be less than `xlen`:
https://github.com/microsoft/cheriot-sail/blob/ef8cfbccdbaf760798449827b5d82ffa2ba9a582/src/cheri_riscv_types.sail#L140

I'm not exactly sure why the Sail compiler thinks `xlen` is equal to 2.

**Comment by rmn30** [comment]
Looks like it might be a recently introduced bug in the Sail compiler. I'll investigate a bit. That type looks a bit odd anyway as I'd expect the result to be in the range 0..2**xlen-1 . Although that doesn't appear to be the proble.

**Comment by marnovandermaas** [comment]
Ok, thanks. May be worth opening up an issue on the Sail repo in that case.

**Comment by Alasdair** [comment]
Should now be fixed in Sail if you pull the latest commit.
