### ISSUE TITLE
Have CJALR create !G sentries?

### ISSUE THREAD

**Issue by nwf-msr** [microsoft/cheriot-sail#63]
Some discussion with Murali about CFI has prompted the question: "can we have `CJALR` create local (`!G`) sentries instead?"  Very little software attempts to do anything with return addresses other than stash them to the stack or use them to return; the examples that leap to mind are things like `setjmp()` and the somehow still holding on `{get,make,set,swap}context()` family of last century, neither of which we have, or have perceived need of, in CHERIoT-RTOS.

I think it would suffice to change https://github.com/microsoft/cheriot-sail/blob/344c9456a6031160183221e5881bd7f3efa3481f/src/cheri_insts.sail#L180 to instead read
```
C(cd) = { sealCap(linkCap, to_bits(cap_otype_width, sentry_type)) with global = false };
```

FWIW, perhaps unsurprisingly, having made that change, we still pass the RTOS test suite.

**Comment by vmurali** [comment]
You need to change the return address cap for CJAL also.

**Comment by nwf-msr** [comment]
Thanks!  For future me, that's, specifically, https://github.com/microsoft/cheriot-sail/blob/344c9456a6031160183221e5881bd7f3efa3481f/src/cheri_insts.sail#L120

**Comment by vmurali** [comment]
Those two changes together passes the RTOS test-suite and all the examples.

**Comment by rmn30** [comment]
The problem with this is that after a call and return you have lost G from PCC. This is required for materialising pointers to read-only globals. Apparently we don't have any thing that requires that in the test suite! 

An alternative is to make a special case in store cap to require store local when sitting a return sentry even if it has G set.

**Comment by rmn30** [comment]
I also wouldn't rule out embedded code using setjmp/longjmp. We could support it only for on stack buffer, which seems reasonable.

**Comment by nwf-msr** [comment]
Ah, right; thanks @rmn30 for the reminder.  I'll close this in favor of another issue for your much better suggestion.
